export const CONFIG_INIT_SUCCESS = 'CONFIG_INIT_SUCCESS';

export const INIT_INVITATIONS_FINISHED = 'INIT_INVITATIONS_FINISHED';
export const INIT_REGISTRATIONS_FINISHED = 'INIT_REGISTRATIONS_FINISHED';
export const REGISTRATION_SETTLED = 'REGISTRATION_SETTLED';
